// Login
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL= 'REFRESH_FAIL';

export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAILURE = 'USER_LOADED_FAILURE';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';

export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAILURE = 'ACTIVATION_FAILURE';

export const LOGOUT = 'LOGOUT';

//Reset Password
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL';

// Test Suits
export const GET_TESTSUITS_SUCCESS = "GET_TESTSUITS_SUCCESS";
export const GET_TESTSUITS_FAIL = "GET_TESTSUITS_FAIL";

// Test Cases
export const GET_TEST_CASES_SUCCESS = "GET_TEST_CASES_SUCCESS";
export const GET_TEST_CASES_FAIL = "GET_TEST_CASES_FAIL";
export const GET_TEST_CASE_SUCCESS = "GET_TEST_CASE_SUCCESS";
export const GET_TEST_CASE_FALE = "GET_TEST_CASE_FALE";
export const GET_TEST_CASES_BY_SUIT_SUCCESS = "GET_TEST_CASES_BY_SUIT_SUCCESS";
export const GET_TEST_CASES_BY_SUIT_FAIL = "GET_TEST_CASES_BY_SUIT_FAIL";
export const SEARCH_CASES_SUCCESS = "SEARCH_CASES_SUCCESS";
export const SEARCH_CASES_FAIL = "SEARCH_CASES_FAIL";
