# Generated by Django 4.1.3 on 2022-11-22 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_suite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuit',
            name='suit_id',
            field=models.CharField(default=datetime.datetime.now, max_length=255, unique=True),
        ),
    ]
